name: ci

on:
  push:
    branches: [main]
  pull_request:

env:
  FOUNDRY_PROFILE: ci

jobs:
  tests:
    strategy:
      fail-fast: true
    name: Tests
    runs-on: ubuntu-latest
    env:
      OPTIMISM_RPC: ${{ secrets.OPTIMISM_RPC }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build
      - name: Run Forge tests
        run: |
          forge test -vv
        id: test

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install Dependencies
        run: yarn
      - name: Lint
        run: yarn lint

  deploy:
    strategy:
      fail-fast: true
    name: Deploy
    runs-on: ubuntu-latest
    env:
      PRIVATE_KEY: "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build
      - name: Start Anvil
        run: anvil --fork-url ${{ secrets.OPTIMISM_RPC }} &
      - name: Wait for Anvil to start running
        run: sleep 10
      - name: Deploy Tokenomics
        run: forge script script/deployments/01_Tokenomics.s.sol --fork-url http://localhost:8545 --broadcast
      - name: Deploy Protocol
        run: forge script script/deployments/02_Protocol.s.sol --fork-url http://localhost:8545 --broadcast
      - name: Enable Fees
        run: forge script script/deployments/03_EnableFees.s.sol --fork-url http://localhost:8545 --broadcast
      - name: Deploy Timelock
        run: forge script script/deployments/04_Timelock.s.sol --fork-url http://localhost:8545 --broadcast
