name: ci

on:
  push:
    branches: [main]
  pull_request:

env:
  FOUNDRY_PROFILE: ci

jobs:
  tests:
    strategy:
      fail-fast: true
    name: Tests
    runs-on: ubuntu-latest
    env:
      OPTIMISM_RPC: ${{ secrets.OPTIMISM_RPC }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: RPC Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.foundry/cache/rpc
          key: ${{ runner.os }}-rpc-${{ hashFiles('**/ForkBlock.sol') }}
      - name: Build Cache
        uses: actions/cache@v3
        with:
          path: |
            cache/
            out/
          key: ${{ runner.os }}-build-${{ github.run_id }}
          restore-keys: ${{ runner.os }}-build-
      - name: Run Forge build
        id: build
        run: |
          forge --version
          forge build --sizes
      - name: Run Forge tests
        id: test
        run: forge test -vv --match-path "test/*.t.sol"

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install Dependencies
        run: yarn
      - name: Lint
        run: yarn lint

  deploy:
    strategy:
      fail-fast: true
    name: Deploy
    runs-on: ubuntu-latest
    env:
      PRIVATE_KEY: "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: Build Cache
        uses: actions/cache@v3
        with:
          path: |
            cache/
            out/
          key: ${{ runner.os }}-build-${{ github.run_id }}
          restore-keys: ${{ runner.os }}-build-
      - name: Run Forge build
        id: build
        run: |
          forge --version
          forge build --sizes
      - name: Start Anvil
        run: anvil --fork-url ${{ secrets.OPTIMISM_RPC }} &
      - name: Wait for Anvil to start running
        run: sleep 10
      - name: Deploy Tokenomics
        run: forge script script/deployments/01_Tokenomics.s.sol --fork-url http://localhost:8545 --broadcast
      - name: Test Tokenomics
        run: forge test -vv --match-path script/deployments/01_Tokenomics.s.sol --fork-url http://localhost:8545
      - name: Deploy Protocol
        run: forge script script/deployments/02_Protocol.s.sol --fork-url http://localhost:8545 --broadcast
      - name: Test Protocol
        run: forge test -vv --match-path script/deployments/02_Protocol.s.sol --fork-url http://localhost:8545
      - name: Deploy Chainlink Automation Setup
        run: forge script script/deployments/03_ChainlinkAutomationSetup.s.sol --fork-url http://localhost:8545 --broadcast
      - name: Test Chainlink Automation Setup
        run: forge test -vv --match-path script/deployments/03_ChainlinkAutomationSetup.s.sol --fork-url http://localhost:8545
      - name: Enable Fees
        run: forge script script/deployments/04_EnableFees.s.sol --fork-url http://localhost:8545 --broadcast
      - name: Test Enable Fees
        run: forge test -vv --match-path script/deployments/04_EnableFees.s.sol --fork-url http://localhost:8545
      - name: Deploy Timelock
        run: forge script script/deployments/05_Timelock.s.sol --fork-url http://localhost:8545 --broadcast
      - name: Test Timelock
        run: forge test -vv --match-path script/deployments/05_Timelock.s.sol --fork-url http://localhost:8545
